### ISSUE TITLE
Add Readme

### ISSUE THREAD

**Issue by govindbalaji-s** [jboss-outreach/junit-get-started#1]
In the GCI task , "Add a JUnit unit test in junit-get-started repository." it is said that details are present in readme of this project. But there is no readme file in this project.

**Comment by zwliew** [comment]
Yup, there is no README in this project despite it being mentioned in the [GCI task](https://codein.withgoogle.com/tasks/5085162800939008).

If it helps, I could help write a README, if any of the mentors in charge of the task explains what the project is about.

**Comment by zwliew** [comment]
@piyush6348 @apoorvaagupta @man

**Comment by zwliew** [comment]
There's now a readme for this project, so I believe this issue can now be closed.

**Comment by garg-anuj** [comment]
Thanks for reminding @zwliew
